title          : Active subglacial water in the Canadian Arctic: supporting material
author         : Whyjay Zheng et al. 
copyright      : "2024"  
logo           : logo.png
only_build_toc_files: true

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  home_page_in_navbar: false
  baseurl: https://whyjz.github.io/ac-subglacial-lakes

# bibtex_bibfiles:
#  - refs.bib

# bibtex_reference_style: author_year

repository:
  url: https://github.com/whyjz/ac-subglacial-lakes
  branch: main
  path_to_book: jupyter-book

# launch_buttons:
#   notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
#   binderhub_url: "https://mybinder.org"
#   thebe: true
  
execute:
  execute_notebooks : 'off'
  timeout           : 30
  allow_errors      : false
  
latex:
  latex_documents:
     targetname: achydro.tex